version: "3.2"

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
        tmpfs:
            - /usr/share/elasticsearch/data

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    mongo:
        image: mongo:4.4
        ports:
            - "27017:27017"
        tmpfs:
            - /data/db

