version: "3.2"
services:

  mongodb:
    image: mongo:4
    networks:
      - superdesk
    expose:
      - "27017"
    ports:
      - "27017:27017"

  redis:
    image: redis:3
    networks:
      - superdesk
    expose:
      - "6379"
    ports:
      - "6379:6379"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    networks:
      - superdesk
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"

  superdesk-server:
    image: sourcefabricoss/superdesk-server:latest
    depends_on:
      - redis
      - mongodb
      - elastic
    environment:
      - SUPERDESK_URL=http://localhost:8080/api
      - DEMO_DATA=1 # install demo data, set to 0 if you want clean install
      - WEB_CONCURRENCY=2
      - SUPERDESK_CLIENT_URL=http://localhost:8080
      - CONTENTAPI_URL=http://localhost:8080/capi
      - MONGO_URI=mongodb://mongodb/superdesk
      - CONTENTAPI_MONGO_URI=mongodb://mongodb/superdesk_capi
      - PUBLICAPI_MONGO_URI=mongodb://mongodb/superdesk_papi
      - LEGAL_ARCHIVE_URI=mongodb://mongodb/superdesk_legal
      - ARCHIVED_URI=mongodb://mongodb/superdesk_archive
      - ELASTICSEARCH_URL=http://elastic:9200
      - ELASTICSEARCH_INDEX=superdesk
      - CELERY_BROKER_URL=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/1
      - DEFAULT_TIMEZONE=Europe/Prague
      - SECRET_KEY=*k^&9)byk=8en9n1sg7-xj4f8wr2mh^x#t%_2=1=z@69oxt50!
      # More configuration options can be found at https://superdesk.readthedocs.io/en/latest/settings.html
    networks:
      - superdesk

  superdesk-client:
    image: sourcefabricoss/superdesk-client:latest
    environment:
      # If not hosting on localhost, change these lines
      - SUPERDESK_URL=http://localhost:8080/api
      - SUPERDESK_WS_URL=ws://localhost:8080/ws
      - IFRAMELY_KEY
    depends_on:
      - superdesk-server
    ports:
      - "8080:80"
    networks:
      - superdesk

networks:
    superdesk:
        driver: bridge
