version: "3.2"
services:

  mongo:
    image: mongo:4.4
    ports:
        - "27017:27017"

  redis:
    image: redis:3
    ports:
        - "6379:6379"
    
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
        - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  superdesk-server:
    image: sourcefabricoss/superdesk-server:latest
    depends_on:
      - redis
      - mongo
      - elastic
    environment:
      - WEB_CONCURRENCY=2
      # If not hosting on localhost, change this line
      - SUPERDESK_CLIENT_URL=http://localhost:8080
      - MONGO_URI=mongodb://mongo/test
      - CONTENTAPI_MONGO_URI=mongodb://mongo/test_ca
      - PUBLICAPI_MONGO_URI=mongodb://mongo/test_pa
      - LEGAL_ARCHIVE_URI=mongodb://mongo/test_la
      - ARCHIVED_URI=mongodb://mongo/test_ar
      - ELASTICSEARCH_URL=http://elastic:9200
      - ELASTICSEARCH_INDEX=superdesk
      - CELERY_BROKER_URL=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/1
      # More configuration options can be found at https://superdesk.readthedocs.io/en/latest/settings.html

  superdesk-client:
    image: sourcefabricoss/superdesk-client:latest
    environment:
      # If not hosting on localhost, change these lines
      - SUPERDESK_URL=http://localhost:8080/api
      - SUPERDESK_WS_URL=ws://localhost:8080/ws
    depends_on:
      - superdesk-server
    ports:
      - "8080:80"
