logstash:
  extends:
    file: common.yml
    service: logstash
  links:
  - elastic

mongodb:
  extends:
    file: common.yml
    service: mongodb
  ports:
    - "27017:27017"

redis:
  extends:
    file: common.yml
    service: redis

kibana:
  extends:
    file: common.yml
    service: kibana
  links:
  - elastic
  ports:
  - "5601:5601"

elastic:
  extends:
    file: common.yml
    service: elastic
  ports:
    - "9200:9200"

postfix:
  extends:
    file: common.yml
    service: postfix

superdesk:
  extends:
    file: common.yml
    service: superdesk
  links:
   - mongodb
   - redis
   - elastic
   - logstash
   - postfix
   - pubapi
  environment:
   - MONGO_URI=mongodb://mongodb/superdesk_e2e
   - SUPERDESK_URL=http://localhost:5000/api
   - SUPERDESK_WS_URL=ws://localhost:5050
   - SUPERDESK_CLIENT_URL=http://localhost:9000
   - SUPERDESK_TESTING=true
   - MONGO_DBNAME=superdesk_e2e
   - ELASTICSEARCH_INDEX=superdesk_e2e
   - LEGAL_ARCHIVE_DBNAME=superdesk_e2e_legal_archive
   - ARCHIVED_DBNAME=superdesk_e2e_archived
   - WEB_CONCURRENCY=3
   - WEB_TIMEOUT=5
   - REDIS_URL=redis://redis:6379/1
 
  ports:
   - "5000:5000"
   - "5100:5100"
   - "5400:5400"
   - "9000:9000"
   - "35729:35729"
  volumes:
   - ../server:/opt/superdesk/
   - ../client:/opt/superdesk/client/
   - ../client-core:/opt/superdesk/client-core/
   - ./Procfile-dev:/opt/superdesk/Procfile
   - ./start-e2e.sh:/opt/superdesk/start.sh

pubapi:
  extends:
    file: common.yml
    service: pubapi
  links:
   - mongodb
   - redis
   - elastic
   - logstash
   - postfix
  environment:
   - SUPERDESK_RELOAD=True
   - SUPERDESK_URL=http://localhost:5000/api
   - SUPERDESK_CLIENT_URL=http://localhost:9000
  volumes:
   - ../superdesk-content-api:/opt/superdesk-content-api/
   #- ./Procfile:/opt/superdesk/Procfile
  ports:
   - "5050:5050"
