mongodb:
  extends:
    file: common.yml
    service: mongodb

redis:
  extends:
    file: common.yml
    service: redis

postfix:
  extends:
    file: common.yml
    service: postfix

elastic:
  extends:
    file: common.yml
    service: elastic

superdesk:
  extends:
    file: common.yml
    service: superdesk
  links:
   - redis
   - mongodb
   - elastic
  environment:
   - SUPERDESK_URL=http://localhost:8080/api
   - SUPERDESK_WS_URL=ws://localhost:8080/ws
   - SUPERDESK_CLIENT_URL=http://localhost:8080
  ports:
   - "8080:80"
  volumes:
   - ./superdesk_vhost.conf:/etc/nginx/sites-enabled/superdesk.conf
