mongodb:
  extends:
    file: common.yml
    service: mongodb
  ports:
    - "27017:27017"

redis:
  extends:
    file: common.yml
    service: redis
  ports:
    - "6379:6379"

elastic:
  extends:
    file: common.yml
    service: elastic
  ports:
    - "9200:9200"

superdesk:
  extends:
    file: common.yml
    service: superdesk
  links:
   - mongodb
   - redis
   - elastic
  environment:
   - SUPERDESK_RELOAD=True
   - SUPERDESK_URL=http://localhost:5000/api
   - SUPERDESK_WS_URL=ws://localhost:5050
   - SUPERDESK_CLIENT_URL=http://localhost:9000
   - MONGO_URI=mongodb://mongodb/superdesk
   - PUBLICAPI_MONGO_URI=mongodb://mongodb/superdesk_pa
   - LEGAL_ARCHIVE_URI=mongodb://mongodb/superdesk_la
   - ARCHIVED_URI=mongodb://mongodb/superdesk_ar
  ports:
   - "5000:5000"
   - "5100:5100"
   - "5400:5400"
   - "9000:9000"
   - "35729:35729"
  volumes:
   - ../server:/opt/superdesk/
   - ../client:/opt/superdesk/client/
   - ../client-core:/opt/superdesk/client-core/
   - ./Procfile-dev:/opt/superdesk/Procfile
   - ./start-dev.sh:/opt/superdesk/start.sh
