# logstash:
#   extends:
#     file: common.yml
#     service: logstash
#   links:
#     - elastic

mongodb:
  extends:
    file: common.yml
    service: mongodb

redis:
  extends:
    file: common.yml
    service: redis

kibana:
  extends:
    file: common.yml
    service: kibana
  links:
  - elastic
  ports:
  - "5601:5601"

elastic:
  extends:
    file: common.yml
    service: elastic

postfix:
  extends:
    file: common.yml
    service: postfix

superdesk:
  extends:
    file: common.yml
    service: superdesk
  links:
   - mongodb
   - redis
   - elastic
    # - logstash
   - postfix
  environment:
    - SUPERDESK_URL=http://${DOCKER_IP}/api
    - SUPERDESK_WS_URL=ws://${DOCKER_IP}/ws
    - SUPERDESK_CLIENT_URL=http://${DOCKER_IP}
  ports:
   - "443:443"
   - "80:80"

