language: python

python:
    - "3.4"

services:
    - mongodb
    - elasticsearch
    - redis-server

install: "pip install -r requirements.txt --use-mirrors"

script:
    - nosetests
    - behave --format progress2 --logging-level ERROR
    - LDAP_SERVER="ldap://sourcefabric.org" LDAP_BASE_FILTER="OU=Superdesk Users,dc=sourcefabric,dc=org" behave --format progress2 --logging-level ERROR
    - flake8

sudo: false
