[tool.black]
line-length = 120
target-version = ['py36']
include = '\.py$'
exclude = '''
(
    \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.env
    | env
    | venv
    | _build
    | build
    | dist
)
'''
