#!/usr/bin/env python3

import json
import requests

OS = 'linux'
CHANNEL = 'beta'
BUILDS_URL = 'https://storage.googleapis.com/chromium-browser-continuous/Linux_x64/{}/chrome-linux.zip'
VERSIONS_URL = 'https://omahaproxy.appspot.com/all.json'

payload = {'os': OS, 'channel': CHANNEL}
r = requests.get(VERSIONS_URL, params=payload)
build = r.json()[0]['versions'][0]['branch_base_position']
print(BUILDS_URL.format(build))

