name: "Docker"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - run: docker build .
      working-directory: ./server
      timeout-minutes: 10

  client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - run: docker build .
      working-directory: ./client
      timeout-minutes: 20
