name: "Pytest"

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        required: false
        default: "3.10"
        type: string

jobs:

  pytest:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    services:
      redis:
        image: redis:alpine
        ports:
            - "6379:6379"

      mongo:
        image: mongo:4
        ports:
            - "27017:27017"

      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
        ports:
            - "9200:9200"
        env:
            discovery.type: single-node

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - run: |
        sudo apt-get update
        sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl libexempi-dev

    - run: |
        python -m pip install -U pip wheel setuptools
        python -m pip install -Ur dev-requirements.txt

    - run: pytest

