name: "Server"

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        required: false
        default: "3.10"
        type: string

defaults:
  run:
    working-directory: server

jobs:
  install:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
            - "6379:6379"

      mongo:
        image: mongo:4
        ports:
            - "27017:27017"

      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
        ports:
            - "9200:9200"
        env:
            discovery.type: single-node

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - run: |
        sudo apt-get update
        sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl libexempi-dev

    - run: |
        python -m pip install -U pip wheel setuptools
        python -m pip install -Ur dev-requirements.txt

    - run: |
        honcho run python manage.py app:initialize_data

  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - run: pip install -Ur dev-requirements.txt
    - run: black --check .

  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - run: pip install -Ur dev-requirements.txt
    - run: flake8

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - run: pip install -Ur dev-requirements.txt
    - run: mypy .
